export type ReportRecommendation="run"|"review"|"avoid";
export type ReportRisk={recommendation:ReportRecommendation;score:number};
export type ReportFinding={rule:string;severity:string;confidence:string;explanation:string;filePath:string;lineStart:number;lineEnd:number;excerpt:string};

export function reportVerdict(risk:ReportRisk,findingCount:number){
 if(risk.recommendation==="run")return{tone:"low" as const,title:"Low concern",summary:findingCount===0?"No strong evidence of malicious behavior was found.":`${findingCount===1?"One behavior was":"Several behaviors were"} noted. ${findingCount===1?"It appears":"They appear"} consistent with normal project behavior.`,nextAction:"Review the noted behavior and normal project setup instructions before running the repository."};
 if(risk.recommendation==="review")return{tone:"review" as const,title:"Review before running",summary:"DoubleCheck found behavior that deserves manual review. The evidence below explains what was observed without assuming malicious intent.",nextAction:"Read each finding and verify the cited behavior before running or installing this repository."};
 return{tone:"high" as const,title:"High risk",summary:"Do not run this repository until the findings below are explained and the risky behavior is removed or verified.",nextAction:"Do not run the repository in your normal environment. Ask the maintainer to explain or remove the cited behavior first."};
}

const fallback=(finding:ReportFinding)=>({title:finding.explanation,found:finding.explanation,why:"This behavior can change how software runs or what information it can access, so it is worth understanding before execution.",impact:"If abused, this behavior could affect the machine or data available to the repository. The finding alone does not confirm that outcome.",action:"Inspect the cited code and its callers before running the repository.",evidenceNote:"The highlighted lines are the exact text that matched the rule."});
const copy:Record<string,(finding:ReportFinding)=>ReturnType<typeof fallback>>={
 CREDENTIAL_ACCESS:()=>({title:"Reads sensitive application configuration",found:"The application reads database settings, credentials, or secret-like values from environment variables.",why:"Malicious code sometimes reads credentials before logging them or sending them elsewhere.",impact:"If abused, retrieved credentials could be exposed or used to access connected services. This finding does not show that such exposure occurred.",action:"Keep real values only in a local .env file or deployment secret manager, never commit them, and inspect where the retrieved values are used.",evidenceNote:"These lines read named environment variables. Reading them is common in backend configuration and is not evidence of theft by itself."}),
 DOWNLOAD_EXEC:()=>({title:"Downloads content and passes it toward execution",found:"A command downloads content and then runs or invokes it.",why:"Downloaded code can change without a repository commit and may execute with the current user's permissions.",impact:"If the remote content were malicious, it could run commands or modify data. DoubleCheck has not executed or verified the downloaded content.",action:"Remove the command or inspect and pin the downloaded artifact before running it.",evidenceNote:"The highlighted command combines a network download with an execution step."}),
 CHILD_PROCESS:()=>({title:"Starts another program or command",found:"The code launches a child process or operating-system command.",why:"Child processes can perform actions outside the application's normal language runtime.",impact:"If abused, the command could read files, change the system, or start additional software. The cited line does not confirm harmful intent.",action:"Check the exact command, its arguments, and when this code runs.",evidenceNote:"The highlighted line contains the process-launch operation."}),
 ENCODED_EXEC:()=>({title:"Decodes data for execution",found:"The code decodes or evaluates encoded content.",why:"Encoding can hide the instructions that will actually run.",impact:"If the decoded content were hostile, it could execute concealed commands. The finding does not prove the payload is malicious.",action:"Decode and review the payload safely before allowing this code to run.",evidenceNote:"The highlighted line joins decoding with evaluation or execution."}),
 PERSISTENCE:()=>({title:"May configure automatic startup",found:"The code references a mechanism that can run software automatically later.",why:"Persistence is legitimate for some applications but is also used by malware to survive restarts.",impact:"If active, the software could start without the user launching it. Confirm the actual control flow before treating this as confirmed behavior.",action:"Verify why automatic startup is needed and remove it if it is unexpected.",evidenceNote:"The highlighted line references an operating-system persistence mechanism."}),
 PACKAGE_LIFECYCLE:()=>({title:"Runs automatically during package installation",found:"A package lifecycle script can run without a separate manual command.",why:"Install hooks execute before a user has had a chance to inspect the installed application.",impact:"If abused, the hook could run commands with the installing user's permissions. Automatic execution is not necessarily malicious.",action:"Inspect the referenced script before running the package manager install command.",evidenceNote:"The highlighted package script is an automatic lifecycle hook."}),
 SUSPICIOUS_EXECUTABLE_FILE:()=>({title:"Includes an executable or script-like file",found:"The repository contains a file that may be directly executable.",why:"Executable files cannot be understood from their name alone and may perform actions outside normal source review.",impact:"Running the file could change the system or access local data. DoubleCheck did not execute it.",action:"Do not open or run the file until its origin and contents are verified.",evidenceNote:"The file path matched an executable or script-like format."}),
 README_SCRIPT_MISMATCH:()=>({title:"Documentation references a missing script",found:"The documentation tells users to run a package script that is not defined in the analyzed package configuration.",why:"A mismatch can be an innocent documentation error, but it makes the real execution path unclear.",impact:"Following inaccurate instructions may fail or encourage users to run an unintended alternative command.",action:"Ask the maintainer to correct the instructions and verify the intended command.",evidenceNote:"The documented command does not match a script in the selected package configuration."})
};

export function findingNarrative(finding:ReportFinding,recommendation:ReportRecommendation){
 const text=(copy[finding.rule]??fallback)(finding);
 const assessment=recommendation==="run"?(finding.rule==="CREDENTIAL_ACCESS"?"Likely normal configuration":"Not necessarily malicious"):recommendation==="review"?"Requires review":"Strongly suspicious";
 const meaning=finding.rule==="CREDENTIAL_ACCESS"&&recommendation==="run"?"This appears consistent with normal backend configuration. DoubleCheck did not find evidence in this finding that the values are logged, written to a file, or sent to an external server.":recommendation==="avoid"?"The surrounding report contains high-risk evidence. Treat this behavior as strongly suspicious until its purpose is verified.":"This behavior can be legitimate, but the surrounding context needs manual review before the repository is run.";
 return{...text,assessment,meaning};
}
