import {extractDocumentedCommands} from "./commands";

export const STATIC_RULESET_VERSION="2026-10-01.v5";
type InputFile={path:string;content?:string|null;selected:boolean;skipReason?:string|null;size:number};
type Severity="low"|"medium"|"high";type Confidence="low"|"medium"|"high";
type ExecutionContext="shell"|"powershell"|"javascript"|"python"|"dockerfile"|"workflow"|"package"|"none";
export type StaticFinding={rule:string;severity:Severity;confidence:Confidence;explanation:string;filePath:string;lineStart:number;lineEnd:number;excerpt:string};
export type AnalysisNote={path:string;disposition:"execution_rules_skipped"|"reduced_confidence"|"content_override";reason:string};

const suspiciousExtensions=/\.(exe|dll|msi|scr|com|bat|cmd|ps1|jar|appimage)$/i;
const generatedOrVendorPath=/(^|\/)(vendor|dist|static|public|generated)(\/|$)|\.min\.[^.]+$/i;
const shellDownloadExec=/\b(?:curl|wget)\b[^\n#]{0,1000}(?:\|\s*(?:sh|bash|zsh|dash|ksh|powershell|pwsh)\b|(?:&&|;)\s*(?:chmod\s+\+x\b[^;&\n]*(?:&&|;)\s*[^;&\n]+|(?:sh|bash|zsh|dash|ksh|powershell|pwsh)\b|\.\/[^\s;&]+))/i;
const powershellDownloadExec=/\b(?:Invoke-WebRequest|Invoke-RestMethod|iwr|irm|curl)\b[^\n#]{0,1000}(?:\|\s*(?:Invoke-Expression|iex)\b|;\s*(?:Start-Process|Invoke-Expression|iex|&\s*\$?\w+))/i;
const jsDownloadExec=/(?:\beval\s*\(\s*(?:await\s+)?(?:\(\s*await\s+)?fetch\s*\(|\bfetch\s*\([^;\n]{0,500}\.then\s*\([^;\n]{0,300}\.then\s*\(\s*eval\b|\b(?:exec|execSync|spawn|spawnSync)\s*\(\s*[`'"][^`'"\n]*(?:curl|wget)\b[^`'"\n]*(?:\|\s*(?:sh|bash|zsh)|&&\s*(?:sh|bash|chmod)|;\s*(?:sh|bash)))/i;
const pythonDownloadExec=/(?:\b(?:exec|eval)\s*\(\s*(?:requests\.(?:get|post)|urllib\.request\.urlopen)\s*\(|\b(?:subprocess\.(?:run|call|Popen)|os\.system)\s*\(\s*[rubf]*["'][^"'\n]*(?:curl|wget)\b[^"'\n]*(?:\|\s*(?:sh|bash|zsh)|&&\s*(?:sh|bash|chmod)|;\s*(?:sh|bash)))/i;

function evidence(rule:string,severity:Severity,explanation:string,path:string,line:number,excerpt:string,confidence:Confidence="medium"):StaticFinding{return{rule,severity,confidence,explanation,filePath:path,lineStart:line,lineEnd:line,excerpt:excerpt.trim().slice(0,500)}}
function extensionContext(path:string):ExecutionContext{const lower=path.toLowerCase(),name=lower.split("/").at(-1)??lower;if(name==="dockerfile"||name.startsWith("dockerfile."))return"dockerfile";if(lower.startsWith(".github/workflows/")&&/\.ya?ml$/.test(lower))return"workflow";if(name==="package.json")return"package";if(/\.(?:sh|bash|zsh|dash|ksh|bat|cmd)$/.test(lower))return"shell";if(/\.ps1$/.test(lower))return"powershell";if(/\.(?:js|cjs|mjs|ts|tsx|jsx)$/.test(lower))return"javascript";if(/\.py$/.test(lower))return"python";return"none"}
function contentContext(content:string):ExecutionContext{const head=content.slice(0,4000);if(/^#!.*\b(?:sh|bash|zsh|dash|ksh)\b/m.test(head))return"shell";if(/^#!.*\b(?:pwsh|powershell)\b/m.test(head)||/\b(?:Invoke-WebRequest|Invoke-RestMethod|Start-Process)\b/.test(head))return"powershell";if(/^#!.*\bpython\d*\b/m.test(head)||/(?:^|\n)\s*(?:from\s+\w+\s+import|import\s+(?:requests|urllib|subprocess|os)\b|def\s+\w+\s*\()/m.test(head))return"python";if(/^#!.*\bnode\b/m.test(head)||/(?:\b(?:const|let|var)\s+\w+\s*=|\brequire\s*\(|\bimport\s+.+\s+from\s+|=>|\bfetch\s*\()/m.test(head))return"javascript";return"none"}
function isMinified(content:string){const lines=content.split(/\r?\n/);return content.length>10_000&&lines.length<=5&&Math.max(...lines.map(line=>line.length))>5_000}
function maskCommentsAndStrings(content:string,context:ExecutionContext){const slash=context==="javascript",hash=["shell","powershell","python","workflow","dockerfile"].includes(context);let output="",quote="",lineComment=false,blockComment=false,escaped=false;for(let i=0;i<content.length;i++){const char=content[i],next=content[i+1];if(lineComment){if(char==="\n"){lineComment=false;output+="\n"}else output+=" ";continue}if(blockComment){if(char==="*"&&next==="/"){output+="  ";i++;blockComment=false}else output+=char==="\n"?"\n":" ";continue}if(quote){if(escaped){escaped=false;output+=" ";continue}if(char==="\\"){escaped=true;output+=" ";continue}if(char===quote){quote="";output+=" "}else output+=char==="\n"?"\n":" ";continue}if(slash&&char==="/"&&next==="/"){output+="  ";i++;lineComment=true;continue}if(slash&&char==="/"&&next==="*"){output+="  ";i++;blockComment=true;continue}if(hash&&char==="#"){output+=" ";lineComment=true;continue}if(char==="'"||char==='"'||(context==="javascript"&&char==="`")){quote=char;output+=" ";continue}output+=char}return output}
const stripComments=maskCommentsAndStrings;
function lineAt(content:string,index:number){return content.slice(0,index).split(/\r?\n/).length}
function downloadExecMatch(content:string,context:ExecutionContext){const executable=maskCommentsAndStrings(content,context);const regex=context==="powershell"?powershellDownloadExec:context==="javascript"?jsDownloadExec:context==="python"?pythonDownloadExec:shellDownloadExec;const match=regex.exec(executable);if(match)return{line:lineAt(executable,match.index),excerpt:content.slice(match.index,match.index+match[0].length)};if(context==="javascript"||context==="python"){const call=context==="javascript"?/\b(?:exec|execSync|spawn|spawnSync)\s*\(/g:/\b(?:subprocess\.(?:run|call|Popen)|os\.system)\s*\(/g;for(const candidate of executable.matchAll(call)){const start=content.lastIndexOf("\n",candidate.index)+1,end=content.indexOf("\n",candidate.index),line=content.slice(start,end<0?content.length:end);if(shellDownloadExec.test(line))return{line:lineAt(content,start),excerpt:line}}}return null}
function coalesceCredentialBlocks(findings:StaticFinding[]){const normalized:StaticFinding[]=[];for(const finding of findings){const previous=normalized.at(-1);if(finding.rule==="CREDENTIAL_ACCESS"&&previous?.rule==="CREDENTIAL_ACCESS"&&previous.filePath===finding.filePath&&finding.lineStart===previous.lineEnd+1){previous.lineEnd=finding.lineEnd;previous.excerpt=`${previous.excerpt}\n${finding.excerpt}`.slice(0,2000);previous.explanation="Reads environment or credential-like values in one contiguous configuration block";continue}normalized.push({...finding})}return normalized}

export function analyzeStatic(input:{owner:string;repository:string;url:string;sha:string;files:InputFile[];coverage:{inventoryCount:number;inventoryBytes:number;selectedBytes:number}}){
 const findings:StaticFinding[]=[],analysisNotes:AnalysisNote[]=[],languages=new Set<string>(),domains=new Set<string>(),commands=input.files.flatMap(file=>file.content?extractDocumentedCommands(file.path,file.content):[]);const scripts:Record<string,string>={};
 for(const file of input.files){const ext=file.path.split(".").pop()?.toLowerCase();if(ext)languages.add(ext);if(suspiciousExtensions.test(file.path))findings.push(evidence("SUSPICIOUS_EXECUTABLE_FILE","medium","Executable or script-like file requires manual inspection",file.path,1,file.path));if(!file.content)continue;const lines=file.content.split(/\r?\n/),byExtension=extensionContext(file.path),byContent=contentContext(file.content),context=byContent!=="none"?byContent:byExtension,minified=isMinified(file.content),vendorLike=generatedOrVendorPath.test(file.path);for(const line of lines)for(const match of line.matchAll(/https?:\/\/([^\s/'"`]+)/g))domains.add(match[1]);
  if(byContent!=="none"&&byExtension!=="none"&&byContent!==byExtension)analysisNotes.push({path:file.path,disposition:"content_override",reason:`Content looks like ${byContent}; path suggested ${byExtension}. Content context was used.`});else if(byContent!=="none"&&byExtension==="none")analysisNotes.push({path:file.path,disposition:"content_override",reason:`Executable ${byContent} syntax was detected despite a non-executable path.`});
  if(context==="none"&&(minified||vendorLike))analysisNotes.push({path:file.path,disposition:"execution_rules_skipped",reason:"Generated/vendor or minified static data had no executable-language signature; execution rules were not applied."});else if((minified||vendorLike)&&context!=="none")analysisNotes.push({path:file.path,disposition:"reduced_confidence",reason:"Generated/vendor or minified executable content was analyzed with reduced confidence."});
  if(["shell","powershell","javascript","python","dockerfile","workflow"].includes(context)){const matched=downloadExecMatch(file.content,context);if(matched)findings.push(evidence("DOWNLOAD_EXEC","high","Downloads content and passes it toward execution",file.path,matched.line,matched.excerpt,(minified||vendorLike)?"low":"high"))}
  const executable=stripComments(file.content,context);executable.split(/\r?\n/).forEach((line,index)=>{const contextual=context!=="none",sourceLine=lines[index]??line;if(contextual&&/(child_process|execFile\(|spawn\(|subprocess\.|os\.system|Runtime\.getRuntime)/i.test(line))findings.push(evidence("CHILD_PROCESS","medium","Starts another process",file.path,index+1,sourceLine,(minified||vendorLike)?"low":"medium"));if(contextual&&/(eval\s*\(.*(?:atob|base64)|FromBase64String)/i.test(line))findings.push(evidence("ENCODED_EXEC","high","Decodes or evaluates encoded content",file.path,index+1,sourceLine,(minified||vendorLike)?"low":"medium"));if(contextual&&/(schtasks|crontab|systemctl enable|\\CurrentVersion\\Run|LaunchAgents)/i.test(line))findings.push(evidence("PERSISTENCE","high","May configure persistence",file.path,index+1,sourceLine));if(contextual&&/(process\.env|os\.environ|getenv\(|AWS_SECRET|GITHUB_TOKEN|\.ssh)/i.test(line))findings.push(evidence("CREDENTIAL_ACCESS","medium","Reads environment or credential-like values",file.path,index+1,sourceLine));for(const match of line.matchAll(/https?:\/\/([^\s/'"`]+)/g))domains.add(match[1])});
  if(context==="package"){try{const parsed=JSON.parse(file.content) as {scripts?:Record<string,string>};Object.assign(scripts,parsed.scripts??{});for(const [name,value] of Object.entries(parsed.scripts??{})){const line=Math.max(1,lines.findIndex(text=>text.includes(`"${name}"`))+1),matched=downloadExecMatch(value,"shell");if(matched)findings.push(evidence("DOWNLOAD_EXEC","high",`Package script '${name}' downloads content and passes it toward execution`,file.path,line,`${name}: ${value}`,"high"));if(["preinstall","install","postinstall","prepare"].includes(name))findings.push(evidence("PACKAGE_LIFECYCLE","medium",`Package lifecycle script ${name} runs automatically`,file.path,line,`${name}: ${value}`,"high"))}}catch{/* inert malformed JSON */}}
 }
 const documentedScriptNames=new Set(commands.flatMap(command=>[...command.excerpt.matchAll(/npm\s+run\s+([\w:-]+)/g)].map(match=>match[1])));for(const name of documentedScriptNames)if(!(name in scripts)){const command=commands.find(item=>item.excerpt.includes(`run ${name}`));findings.push(evidence("README_SCRIPT_MISMATCH","low",`Documentation references npm script '${name}' but package.json does not define it`,command?.filePath??"README.md",command?.lineStart??1,`npm run ${name}`,"high"))}
 const normalizedFindings=coalesceCredentialBlocks(findings),weights:Record<Severity,number>={low:2,medium:8,high:20},score=Math.min(100,normalizedFindings.reduce((sum,finding)=>sum+weights[finding.severity],0)),paths=new Set(input.files.map(file=>file.path.toLowerCase()));
 return {version:1,rulesetVersion:STATIC_RULESET_VERSION,generatedAt:new Date().toISOString(),repository:{owner:input.owner,name:input.repository,url:input.url,sha:input.sha},noExecution:true,analysisNotes,trustSignals:{license:[...paths].some(path=>/^license(\.|$)/.test(path)),securityPolicy:paths.has("security.md"),codeOwners:paths.has(".github/codeowners"),pinnedCommit:Boolean(input.sha)},coverage:{...input.coverage,selectedCount:input.files.filter(file=>file.selected).length,skipped:input.files.filter(file=>!file.selected).map(file=>({path:file.path,reason:file.skipReason??undefined,size:file.size}))},inventory:{languages:[...languages].sort(),packageManagers:[...new Set(input.files.flatMap(file=>file.path.endsWith("package-lock.json")?["npm"]:file.path.endsWith("pnpm-lock.yaml")?["pnpm"]:file.path.endsWith("yarn.lock")?["yarn"]:file.path.endsWith("poetry.lock")?["poetry"]:[]))],manifests:input.files.filter(file=>/(package\.json|pyproject\.toml|requirements.*\.txt|Cargo\.toml|go\.mod)$/i.test(file.path)).map(file=>file.path),lockfiles:input.files.filter(file=>/(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|poetry\.lock|Cargo\.lock|go\.sum)$/i.test(file.path)).map(file=>file.path),workflows:input.files.filter(file=>file.path.startsWith(".github/workflows/")).map(file=>file.path),scripts,commands,domains:[...domains].sort()},findings:normalizedFindings,risk:{score,recommendation:score>=70?"avoid":score>=20?"review":"run",reason:normalizedFindings.length?`${normalizedFindings.length} deterministic signal(s) require review.`:"No material deterministic rule matched the selected text files."}};
}
