import React from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {describe,expect,it,vi} from "vitest";
import {StaticReportView,type StaticReport} from "../src/components/StaticReportView";

vi.mock("next/navigation",()=>({useRouter:()=>({replace:vi.fn()})}));

const report:StaticReport={rulesetVersion:"test.v1",repository:{owner:"o",name:"r",url:"https://github.com/o/r",sha:"abc"},risk:{recommendation:"run",score:8,reason:"legacy technical reason"},coverage:{inventoryCount:1,inventoryBytes:100,selectedBytes:100,selectedCount:1,skipped:[]},inventory:{languages:["py"],packageManagers:[],manifests:[],workflows:[],commands:[],domains:[]},analysisNotes:[{path:"app/static/swagger-ui.css",disposition:"execution_rules_skipped",reason:"Static minified CSS"}],findings:[{rule:"CREDENTIAL_ACCESS",severity:"medium",confidence:"medium",explanation:"Reads environment values",filePath:"app/config.py",lineStart:4,lineEnd:8,excerpt:'POSTGRES_HOST = os.environ.get("POSTGRES_HOST", "db")\nSECRET_KEY = "correct-horse-battery-staple"'}]};
describe("static report view",()=>{it("renders beginner-facing investigation sections and secondary technical details",()=>{const html=renderToStaticMarkup(<StaticReportView report={report} aiMode="disabled" maxCost={0.25}/>);for(const heading of ["Low concern","What was found?","Why was it flagged?","What does it mean here?","Evidence","Possible impact","Recommended action","Technical details"])expect(html).toContain(heading);expect(html).toContain("<details class=\"technicalDetails\"");expect(html).not.toContain("medium · medium")});it("keeps environment names visible while redacting real values",()=>{const html=renderToStaticMarkup(<StaticReportView report={report} aiMode="disabled" maxCost={0.25}/>);expect(html).toContain("POSTGRES_HOST");expect(html).toContain("SECRET_KEY");expect(html).not.toContain("correct-horse");expect(html).toContain("[REDACTED_SECRET]")});it("marks evidence as horizontally scrollable and keyboard focusable",()=>{const html=renderToStaticMarkup(<StaticReportView report={report} aiMode="disabled" maxCost={0.25}/>);expect(html).toContain('class="code evidenceCode"');expect(html).toContain('tabindex="0"');expect(html).toContain("Analysis disclosures")});it("hides all AI controls and messaging in the static-only release",()=>{const html=renderToStaticMarkup(<StaticReportView id="scan" report={report} aiMode="disabled" maxCost={0.25}/>);expect(html).not.toContain("Optional AI analysis");expect(html).not.toContain("Analyze with AI")});it("renders deterministic counts and accurate optional AI cost wording when local AI is explicitly enabled",()=>{const withBytes={...report,coverage:{...report.coverage,selectedBytes:687293}};const html=renderToStaticMarkup(<StaticReportView id="scan" report={withBytes} aiMode="local" maxCost={0.25}/>);expect(html).toContain("687,293");expect(html).toContain("Analyze with AI");expect(html).toContain("Maximum estimated cost: $0.25");expect(html).toContain("Actual cost depends on token usage");expect(html).not.toContain("Run optional AI")})});
