"use client";
import {useState} from "react";import {readApiResponse} from "@/lib/api-client";import {DeleteReport} from "./DeleteReport";
type Finding={rule:string;severity:string;confidence:string;explanation:string;filePath:string;lineStart:number;lineEnd:number;excerpt:string};
type Note={path:string;disposition:string;reason:string};
export type StaticReport={rulesetVersion:string;repository:{owner:string;name:string;url:string;sha:string};risk:{recommendation:"run"|"review"|"avoid";score:number;reason:string};coverage:{inventoryCount:number;inventoryBytes:number;selectedBytes:number;selectedCount:number;skipped:Array<{path:string;reason?:string;size:number}>};inventory:{languages:string[];packageManagers:string[];manifests:string[];workflows:string[];commands:Array<{filePath:string;lineStart:number;excerpt:string}>;domains:string[]};analysisNotes?:Note[];findings:Finding[]};
type AiReport={models?:{analysis?:string;verifier?:string};decision?:{verdict?:string;reason?:string};usage?:{inputTokens?:number;outputTokens?:number;actualCostMicrousd?:string}};
export function StaticReportView({id,report,aiMode,maxCost,aiError,aiReport,demo=false}:{id?:string;report:StaticReport;aiMode:string;maxCost:number;aiError?:string|null;aiReport?:AiReport|null;demo?:boolean}){
 const [message,setMessage]=useState(aiError??"");async function requestAi(){if(!id)return;try{const payload=await readApiResponse(await fetch(`/api/scans/${id}/ai`,{method:"POST"}));setMessage(payload.status==="completed"?"A matching AI result was reused. Refresh to view it.":"Optional AI analysis is queued. Refresh shortly.")}catch(error){setMessage(error instanceof Error?error.message:"AI request failed")}}
 return <main className="report">
  <div className="reportHead"><div>{demo&&<div className="demoFlag">Sanitized static fixture · no external calls</div>}<p className="muted">Deterministic static analysis · ruleset {report.rulesetVersion}</p><h1 className="repoTitle">{report.repository.owner}/{report.repository.name}</h1><p className="muted">Pinned commit <code>{report.repository.sha}</code></p></div><span className={`badge ${report.risk.recommendation}`}>{report.risk.recommendation} · {report.risk.score}/100</span></div>
  <div className="notice"><strong>{report.risk.reason}</strong><br/>Repository content was treated as untrusted data and was never executed.</div>
  <div className="actions" style={{margin:"18px 0 28px"}}>{id&&<><a className="button secondary" href={`/api/reports/${id}/export?format=json`}>Export JSON</a><a className="button secondary" href={`/api/reports/${id}/export?format=markdown`}>Export Markdown</a><DeleteReport id={id}/></>}</div>
  <div className="grid"><div>
   <section className="card section"><h2>Deterministic findings</h2>{report.findings.length===0?<p className="muted">No configured rule matched.</p>:report.findings.map((finding,index)=><article className="evidence" key={`${finding.rule}-${index}`}><div className="evidenceMeta">{finding.rule} · {finding.severity} · {finding.confidence} · {finding.filePath}:{finding.lineStart}-{finding.lineEnd}</div><h3>{finding.explanation}</h3><pre className="code">{finding.excerpt}</pre></article>)}</section>
   <section className="card section"><h2>Commands found in documentation</h2>{report.inventory.commands.length?report.inventory.commands.map((command,index)=><div className="evidence" key={index}><div className="evidenceMeta">{command.filePath}:{command.lineStart} · recorded, not endorsed</div><pre className="code">{command.excerpt}</pre></div>):<p className="muted">No documented commands recorded.</p>}</section>
   <section className="card section"><h2>Optional AI analysis</h2>{aiReport?<><p><strong>{aiReport.decision?.verdict??"Complete"}</strong> · {aiReport.decision?.reason}</p><p className="muted">Models: {aiReport.models?.analysis} / {aiReport.models?.verifier}; tokens: {(aiReport.usage?.inputTokens??0)+(aiReport.usage?.outputTokens??0)}</p></>:<><p className="muted">Separate from the deterministic report and only started by explicit request.</p>{aiMode==="local"&&id?<button onClick={requestAi}>Run optional AI · maximum ${maxCost.toFixed(2)}</button>:<p>AI is {aiMode==="disabled"?"disabled":"unavailable until authenticated server mode is implemented"}.</p>}</>}{message&&<p className="error" role="alert">{message}</p>}</section>
  </div><aside>
   <section className="card section"><h2>Coverage</h2><div className="facts"><div className="fact"><label>Inventory</label>{report.coverage.inventoryCount}</div><div className="fact"><label>Selected</label>{report.coverage.selectedCount}</div><div className="fact"><label>Skipped</label>{report.coverage.skipped.length}</div><div className="fact"><label>Selected bytes</label>{report.coverage.selectedBytes}</div></div></section>
   <section className="card section"><h2>Repository inventory</h2><p>Languages/extensions: {report.inventory.languages.join(", ")||"none"}</p><p>Package managers: {[...new Set(report.inventory.packageManagers)].join(", ")||"none"}</p><p>Manifests: {report.inventory.manifests.join(", ")||"none"}</p><p>Workflows: {report.inventory.workflows.join(", ")||"none"}</p><p>Endpoints/domains: {report.inventory.domains.join(", ")||"none"}</p></section>
   {report.analysisNotes?.length?<section className="card section"><h2>Analysis disclosures</h2>{report.analysisNotes.slice(0,20).map((note,index)=><p key={`${note.path}-${index}`}><code>{note.path}</code> · {note.disposition.replaceAll("_"," ")} · {note.reason}</p>)}{report.analysisNotes.length>20&&<p>…and {report.analysisNotes.length-20} more.</p>}</section>:null}
   <section className="card section"><h2>Skipped files</h2>{report.coverage.skipped.slice(0,30).map(file=><p key={file.path}><code>{file.path}</code> · {file.reason??"not selected"}</p>)}{report.coverage.skipped.length>30&&<p>…and {report.coverage.skipped.length-30} more.</p>}</section>
  </aside></div>
 </main>;
}
